services:

  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "8200:3000"
    environment: 
      - ACCOUNT_REGISTRATION=false
      - JWT_SECRET=dCYlN0UjXA0sO4lQaz0JxMd11U1c0lausHwKrW1Jat8=    #generate-with: openssl rand -base64 32
      - HTTP_ALLOWED=false
      - ALLOW_UNAUTHENTICATED=false
      - AUTO_DELETE_EVERY_N_HOURS=24
    volumes:
      -./convertx:/app/data
